crossposting/posts/__init__.py
from flask import Blueprint

posts_page = Blueprint('posts_page', __name__)

from . import views

crossposting/posts/views.py
from flask import abort, render_template, flash, redirect, url_for
from . import posts_page
from ..models import Post
from .. import db


@posts_page.route('/', methods=['GET', 'POST'])
def list_posts():
    """
    List all posts
    """
    posts = Post.query.all()

    try:
        return render_template('posts/posts.html', posts=posts, title="Posts")
    except:
        abort(404)


@posts_page.route('/delete/<int:id>', methods=['GET', 'POST'])
def delete_post(id):
    """
    Delete a post from the database
    """
    posts = Post.query.get_or_404(id)
    db.session.delete(posts)
    db.session.commit()
    flash('You have successfully deleted the post.')

    # redirect to the posts page
    return redirect(url_for('posts_page.list_posts'))

crossposting/templates/posts/posts.html
{% import "bootstrap/utils.html" as utils %}
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block body %}
<div class="content-section">
    <div class="outer">
        <div class="middle">
            <div class="inner">
                <br/>
                {{ utils.flashed_messages() }}
                <br/>
                <h1 style="text-align:center;">{{ title }}</h1>
                {% if posts %}
                <hr class="intro-divider">
                <div class="center-posts">
                    <table class="table table-striped table-bordered">
                        <thead>
                        <tr>
                            <th width="10%">Channel Id</th>
                            <th width="10%">Telegram Id</th>
                            <th width="70%">Post</th>
                            <th width="10%">Photo(s)</th>
                            <th width="10%">Document(s)</th>
                            <th width="10%">Web preview(s)</th>
                            <th width="10%">Video(s)</th>
                            <th width="10%">Gif(s)</th>
                            <th width="10%">Pole(s)</th>
                            <th width="15%">Grouped Id</th>
                            <th width="10%">Date</th>
                            <th width="10%">Sent</th>
                            <th width="10%">Delete</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for post in posts %}
                        <tr>
                            <td>{{ post.channel_id }}</td>
                            <td>{{ post.tg_id }}</td>
                            <td>{{ post.message }}</td>
                            <td>{{ post.is_photo }}</td>
                            <td>{{ post.is_document }}</td>
                            <td>{{ post.is_web_preview }}</td>
                            <td>{{ post.is_video }}</td>
                            <td>{{ post.is_gif }}</td>
                            <td>{{ post.is_pole }}</td>
                            <td>{{ post.grouped_id }}</td>
                            <td>{{ post.date }}</td>
                            <td>{{ post.sent }}</td>
                            <td>
                                <a href="{{ url_for('posts_page.delete_post', id=post.id) }}">
                                    <i class="fa fa-trash"></i> Delete
                                </a>
                            </td>
                        </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
                <div style="text-align: center">
                    {% else %}
                    <div style="text-align: center">
                        <h3> No posts have been added. </h3>
                        <hr class="intro-divider">
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}